-- =============================================
-- US4: NSE Top 50 Stocks Master Data
-- File: src/main/resources/data.sql
-- Auto-loaded by Spring Boot on startup
-- =============================================

INSERT IGNORE INTO stocks (company_name, ticker_symbol, exchange) VALUES
('Reliance Industries Ltd', 'RELIANCE', 'NSE'),
('Tata Consultancy Services', 'TCS', 'NSE'),
('HDFC Bank Ltd', 'HDFCBANK', 'NSE'),
('Infosys Ltd', 'INFY', 'NSE'),
('ICICI Bank Ltd', 'ICICIBANK', 'NSE'),
('Hindustan Unilever Ltd', 'HINDUNILVR', 'NSE'),
('ITC Ltd', 'ITC', 'NSE'),
('State Bank of India', 'SBIN', 'NSE'),
('Bharti Airtel Ltd', 'BHARTIARTL', 'NSE'),
('Kotak Mahindra Bank', 'KOTAKBANK', 'NSE'),
('Larsen and Toubro Ltd', 'LT', 'NSE'),
('Axis Bank Ltd', 'AXISBANK', 'NSE'),
('Asian Paints Ltd', 'ASIANPAINT', 'NSE'),
('Maruti Suzuki India', 'MARUTI', 'NSE'),
('HCL Technologies Ltd', 'HCLTECH', 'NSE'),
('Sun Pharmaceutical', 'SUNPHARMA', 'NSE'),
('Titan Company Ltd', 'TITAN', 'NSE'),
('UltraTech Cement Ltd', 'ULTRACEMCO', 'NSE'),
('Bajaj Finance Ltd', 'BAJFINANCE', 'NSE'),
('Wipro Ltd', 'WIPRO', 'NSE'),
('ONGC Ltd', 'ONGC', 'NSE'),
('Power Grid Corporation', 'POWERGRID', 'NSE'),
('NTPC Ltd', 'NTPC', 'NSE'),
('Tech Mahindra Ltd', 'TECHM', 'NSE'),
('Nestle India Ltd', 'NESTLEIND', 'NSE'),
('Bajaj Finserv Ltd', 'BAJAJFINSV', 'NSE'),
('JSW Steel Ltd', 'JSWSTEEL', 'NSE'),
('Tata Motors Ltd', 'TATAMOTORS', 'NSE'),
('Adani Enterprises Ltd', 'ADANIENT', 'NSE'),
('Adani Ports and SEZ', 'ADANIPORTS', 'NSE'),
('Coal India Ltd', 'COALINDIA', 'NSE'),
('Britannia Industries', 'BRITANNIA', 'NSE'),
('Divi Laboratories', 'DIVISLAB', 'NSE'),
('Dr Reddys Laboratories', 'DRREDDY', 'NSE'),
('Eicher Motors Ltd', 'EICHERMOT', 'NSE'),
('Grasim Industries Ltd', 'GRASIM', 'NSE'),
('Hero MotoCorp Ltd', 'HEROMOTOCO', 'NSE'),
('Hindalco Industries', 'HINDALCO', 'NSE'),
('IndusInd Bank Ltd', 'INDUSINDBK', 'NSE'),
('Mahindra and Mahindra', 'MM', 'NSE'),
('SBI Life Insurance', 'SBILIFE', 'NSE'),
('HDFC Life Insurance', 'HDFCLIFE', 'NSE'),
('Cipla Ltd', 'CIPLA', 'NSE'),
('Apollo Hospitals', 'APOLLOHOSP', 'NSE'),
('Bajaj Auto Ltd', 'BAJAJ-AUTO', 'NSE'),
('BPCL Ltd', 'BPCL', 'NSE'),
('Tata Consumer Products', 'TATACONSUM', 'NSE'),
('Tata Steel Ltd', 'TATASTEEL', 'NSE'),
('UPL Ltd', 'UPL', 'NSE'),
('Vedanta Ltd', 'VEDL', 'NSE');
